### ISSUE TITLE
Plugin fails with Docker 18.04

### ISSUE THREAD

**Issue by avsm** [buildkite-plugins/docker-login-buildkite-plugin#3]
This change in Docker 18.04 deprecates unencrypted creds storage, which means this plugin doesn't work out of the box as the command goes interactive. https://github.com/docker/cli/pull/561/files

I think that passing `--password-stdin` might work around this, instead of the `--password` currently used.

**Comment by avsm** [comment]
It looks like this has been temporarily reverted to the old behaviour in Docker 18.05, but the issue will still crop up in a few releases as the functionality is deprecated more slowly.

https://github.com/docker/cli/pull/1008

**Comment by toolmantim** [comment]
Thanks for taking the time to file this, and for the heads up. I've released v1.1.0 with a version that uses STDIN instead.

**Comment by avsm** [comment]
A belated thank you for fixing this @toolmantim -- and confirming that it's working great on the latest Docker 18.05 CE edition for me.

**Comment by toolmantim** [comment]
Woohoo! No worries. Thanks for taking the time to come and report back 🎉
