### ISSUE TITLE
Retry for HTTP failure?

### ISSUE THREAD

**Issue by geoffharcourt** [buildkite-plugins/docker-login-buildkite-plugin#46]
We've seen our builds fail a few times today due to what looks like some intermittent connectivity when authenticating with Docker:

```
Logging into docker registry hub.docker.com | 3s
-- | --
  | Error response from daemon: Get https://registry-1.docker.io/v2/: Get https://auth.docker.io/token?account=<redacted>&client_id=docker&offline_token=true&service=registry.docker.io: EOF
--
  | 🚨 Error: The plugin docker-login pre-command hook exited with status 1

```

Could we establish an option to retry authentication without needing a general job retry?

**Comment by keithduncan** [comment]
Hi @geoffharcourt! This is actually on my radar to add to an Elastic CI Stack release along with https://github.com/buildkite-plugins/ecr-buildkite-plugin/pull/62. I’m going to re-open it for my own tracking 😄
