### ISSUE TITLE
docker-login plugin does not logout

### ISSUE THREAD

**Issue by fiedlerdemos** [buildkite-plugins/docker-login-buildkite-plugin#71]
In my pipeline.yml I used:
      - docker-login#v2.1.0:
          username: xxxx
          password-env: MY_DOCKER_LOGIN_PASSWORD
Every thing ok.
But after termination of pipeline in  /var/lib/buildkite-agent/.docker/config.json remains with authentication information and not empty as it would be after appropriate logout. 
So everyone using this agent can manipulate docker repos.

**Comment by toote** [comment]
@fiedlerdemos that is actually a great find and points to a deeper issue when an instance has several agents as well. I will see what can be done about it
